# To create this deployment and service:
# 1. Create Deployment using: kubectl apply -f webapp-deploy.yaml

# -------------------------------------------------------------
# To verify resources:
# kubectl get pods -l app=webapp
# kubectl get deployment webapp-deployment
# kubectl get service webapp-service
# kubectl describe pod <pod-name>
# kubectl logs <pod-name>


# ---------------------- WebApp Deployment ----------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webappdb
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 9000  # App listens on port 9000 inside the container

---

# ---------------------- WebApp Service ----------------------
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 9000        # ClusterIP service port
      targetPort: 3000  # Forward traffic to container's internal port 3000
      nodePort: 30200   # Expose service on this static port on every node
